"""
Integration fidelity test: seeded PYSTILT vs seeded R-STILT reference.

This module runs a real PYSTILT simulation against the 01-wbb tutorial
meteorology, forcing deterministic HYSPLIT settings with ``krand=2`` and
``seed=42``. The resulting trajectory parquet and footprint NetCDF are then
compared directly against the committed R-STILT fixtures generated by
``tests/fixtures/generate_r_ref.sh``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest
import xarray as xr

from stilt.model import Model

from ..fixtures.r_stilt_reference import (
    REFERENCE_FOOTPRINT_PATH,
    REFERENCE_KRAND,
    REFERENCE_SEED,
    REFERENCE_TRAJECTORY_COMPARE_COLUMNS,
    REFERENCE_TRAJECTORY_PATH,
    reference_model_config,
    reference_python_sim_id,
    reference_receptor,
)
from .conftest import integration


def _sorted_trajectory(df: pd.DataFrame) -> pd.DataFrame:
    """Return trajectory rows sorted into a stable comparison order."""
    return (
        df[REFERENCE_TRAJECTORY_COMPARE_COLUMNS]
        .sort_values(by=["indx", "time"])
        .reset_index(drop=True)
    )


@pytest.fixture(scope="module")
def r_traj() -> pd.DataFrame:
    """Seeded R-STILT reference trajectory fixture."""
    return pd.read_parquet(REFERENCE_TRAJECTORY_PATH)


@pytest.fixture(scope="module")
def r_foot_ds() -> xr.Dataset:
    """Seeded R-STILT reference footprint fixture."""
    ds = xr.open_dataset(REFERENCE_FOOTPRINT_PATH)
    ds.load()
    ds.close()
    return ds


@pytest.fixture(scope="module")
def fidelity_config(met_dir):
    """Deterministic config matching the committed R-STILT fixture run."""
    return reference_model_config(met_dir)


@pytest.fixture(scope="module")
def py_outputs(tmp_path_factory, fidelity_config) -> dict[str, Path]:
    """Run one seeded PYSTILT simulation and return its output paths."""
    project_dir = tmp_path_factory.mktemp("r_stilt_fidelity")
    receptor = reference_receptor()
    model = Model(project=project_dir, config=fidelity_config, receptors=[receptor])
    model.run()

    sim_id = reference_python_sim_id()
    sim_dir = model.layout.project_dir / "simulations" / "by-id" / sim_id

    return {
        "sim_dir": sim_dir,
        "traj": next(sim_dir.glob("*_traj.parquet")),
        "foot": next(sim_dir.glob("*_foot.nc")),
        "setup": sim_dir / "SETUP.CFG",
    }


@integration
def test_setup_cfg_pins_krand_and_seed(py_outputs) -> None:
    """The deterministic fidelity run writes the expected RNG controls."""
    content = py_outputs["setup"].read_text().lower()

    assert f"krand={REFERENCE_KRAND}" in content
    assert f"seed={REFERENCE_SEED}" in content


@integration
def test_seeded_trajectory_matches_r_fixture(py_outputs, r_traj: pd.DataFrame) -> None:
    """Seeded PYSTILT trajectory matches the committed seeded R-STILT reference."""
    py_traj = pd.read_parquet(py_outputs["traj"])

    assert len(py_traj) == len(r_traj)
    assert set(REFERENCE_TRAJECTORY_COMPARE_COLUMNS) <= set(py_traj.columns)

    py_sorted = _sorted_trajectory(py_traj)
    r_sorted = _sorted_trajectory(r_traj)

    np.testing.assert_array_equal(
        py_sorted["indx"].to_numpy(), r_sorted["indx"].to_numpy()
    )
    np.testing.assert_array_equal(
        py_sorted["time"].to_numpy(), r_sorted["time"].to_numpy()
    )

    np.testing.assert_allclose(
        py_sorted.drop(columns=["indx", "time"]).to_numpy(dtype=float),
        r_sorted.drop(columns=["indx", "time"]).to_numpy(dtype=float),
        rtol=1e-7,
        atol=1e-10,
        err_msg="Seeded trajectory values differ from the R-STILT reference.",
    )


@integration
def test_seeded_footprint_matches_r_fixture(py_outputs, r_foot_ds: xr.Dataset) -> None:
    """Seeded PYSTILT footprint matches the committed seeded R-STILT reference."""
    py_foot_ds = xr.open_dataset(py_outputs["foot"])
    py_foot_ds.load()
    py_foot_ds.close()

    np.testing.assert_array_equal(
        pd.to_datetime(py_foot_ds.time.values),
        pd.to_datetime(r_foot_ds.time.values),
    )
    np.testing.assert_allclose(
        py_foot_ds.lat.values, r_foot_ds.lat.values, rtol=0, atol=1e-12
    )
    np.testing.assert_allclose(
        py_foot_ds.lon.values, r_foot_ds.lon.values, rtol=0, atol=1e-12
    )
    np.testing.assert_allclose(
        py_foot_ds.foot.values.astype(np.float64),
        r_foot_ds.foot.values.astype(np.float64),
        rtol=1e-7,
        atol=1e-12,
        err_msg="Seeded footprint values differ from the R-STILT reference.",
    )
